version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: Test
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: A123456*
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - postgres_network
    ports:
      - "5432:5432"

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
