version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: A123456*
    volumes:
      - ./data:/data/db
    networks:
      - mongodb_network
    ports:
      - "27017:27017"

volumes:
  mongodb_data:

networks:
  mongodb_network:
    driver: bridge
