version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: A123456*
      MYSQL_DATABASE: Test
      MYSQL_USER: sa
      MYSQL_PASSWORD: A123456*
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - mysql_network
    ports:
      - "3306:3306"

volumes:
  mysql_data:

networks:
  mysql_network:
    driver: bridge
